# Generated by Django 5.1.6 on 2026-03-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0014_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='token_invalid_before',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
