# Generated by Django 5.1.6 on 2026-03-25 09:31

import registrar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0018_staff_chat_read_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffchatmessage',
            name='attachment',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=registrar.models.staff_chat_attachment_upload_to),
        ),
        migrations.AddField(
            model_name='staffchatmessage',
            name='attachment_original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='staffchatmessage',
            name='body',
            field=models.CharField(blank=True, default='', max_length=4000),
        ),
    ]
