# Generated by Django 5.1.6 on 2026-04-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0026_continuingfolderstatus'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='continuingfolderstatus',
            new_name='registrar_c_program_26b077_idx',
            old_name='registrar_c_program_ebf6ee_idx',
        ),
        migrations.RenameIndex(
            model_name='continuingfolderstatus',
            new_name='registrar_c_status_d4d755_idx',
            old_name='registrar_c_status_0f3f5c_idx',
        ),
        migrations.AlterField(
            model_name='academichistory',
            name='adviser_approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='academichistory',
            name='dean_approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='academichistory',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, '1st Semester'), (2, '2nd Semester'), (3, 'Summer')]),
        ),
        migrations.AlterField(
            model_name='academichistory',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='ongoing', max_length=20),
        ),
        migrations.AlterField(
            model_name='academicsubject',
            name='status',
            field=models.CharField(choices=[('enrolled', 'Enrolled'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='enrolled', max_length=20),
        ),
        migrations.AlterField(
            model_name='academicterm',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, '1st Semester'), (2, '2nd Semester'), (3, 'Summer')], db_index=True),
        ),
        migrations.AlterField(
            model_name='continuingfolderstatus',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1st Semester'), (2, '2nd Semester'), (3, 'Summer')], null=True),
        ),
        migrations.AlterField(
            model_name='programoffering',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, '1st Semester'), (2, '2nd Semester'), (3, 'Summer')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='prospectusentry',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, '1st Semester'), (2, '2nd Semester'), (3, 'Summer')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='adviser_approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='dean_approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1st Semester'), (2, '2nd Semester'), (3, 'Summer')], null=True),
        ),
        migrations.AlterField(
            model_name='studentload',
            name='status',
            field=models.CharField(choices=[('enrolled', 'Enrolled'), ('passed', 'Passed'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('failed', 'Failed')], default='enrolled', max_length=20),
        ),
    ]
